apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    io.kompose.service: mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - name: mongo-db
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data