apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    io.kompose.service: mongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  ports:
    - name: "27017"
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
  selector:
    io.kompose.service: mongo
